version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432"
    networks:
      - prod-check
  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart
    networks:
      - food-delivery
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prod-check
  app:
    build:
      context: ./crawl-microservice/docker/dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    networks:
      - prod-check
    depends_on:
      - db
      - redis
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_net
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
volumes:
  redis_data:
networks:
  prod-check:
    driver: bridge
